# Generated by Django 2.2.4 on 2019-08-17 14:45

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190817_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(default='default.png', upload_to='avatars'),
        ),
    ]
