# Generated by Django 2.2.4 on 2019-08-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190823_0229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
