# Generated by Django 2.2.8 on 2020-02-07 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200124_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.date(1998, 3, 3)),
            preserve_default=False,
        ),
    ]
