# Generated by Django 2.2.8 on 2020-02-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Mal', 'Male'), ('Fem', 'Female')], default='Mal', max_length=3),
            preserve_default=False,
        ),
    ]
