# Generated by Django 2.2.4 on 2019-12-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_celebrate', models.TimeField()),
                ('end_celebrate', models.TimeField()),
                ('notes', models.TextField(max_length=150)),
            ],
        ),
    ]
