# Generated by Django 2.2.4 on 2020-01-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='end_event',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_event',
            field=models.DateTimeField(),
        ),
    ]
