# Generated by Django 2.2.4 on 2019-08-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
