# Generated by Django 2.2.4 on 2019-09-07 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20190902_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 20, 4, 31, 311884, tzinfo=utc)),
        ),
    ]
