# Generated by Django 2.2.4 on 2019-09-08 16:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20190907_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='done',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='like_comment',
        ),
        migrations.AlterField(
            model_name='comments',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.Album'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 8, 16, 38, 46, 287519, tzinfo=utc)),
        ),
    ]
