# Generated by Django 2.2.4 on 2019-09-08 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20190908_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='album',
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 8, 17, 28, 26, 817497, tzinfo=utc)),
        ),
    ]
