# Generated by Django 2.2.4 on 2019-10-03 21:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20190910_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 21, 59, 56, 684288, tzinfo=utc)),
        ),
    ]
