# Generated by Django 2.2.4 on 2019-10-04 23:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_auto_20191004_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 23, 11, 11, 480732, tzinfo=utc)),
        ),
    ]
