# Generated by Django 2.2.4 on 2019-10-05 01:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_auto_20191005_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 1, 9, 33, 153401, tzinfo=utc)),
        ),
    ]
