# Generated by Django 2.2.4 on 2019-08-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190808_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='author',
        ),
        migrations.AddField(
            model_name='songsalbum',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='music.Person'),
        ),
    ]
