# Generated by Django 2.2.4 on 2019-08-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_songsalbum_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ManyToManyField(blank=True, to='music.SongsAlbum')),
            ],
        ),
    ]
