# Generated by Django 2.2.4 on 2019-08-11 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190808_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songsalbum',
            name='author',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='song',
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='music.Person'),
        ),
        migrations.AddField(
            model_name='vote',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
            preserve_default=False,
        ),
    ]
