# Generated by Django 2.2.4 on 2019-09-02 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20190830_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 6, 49, 5, 577246, tzinfo=utc)),
        ),
    ]
