# Generated by Django 2.2.4 on 2019-09-08 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20190908_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='album',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.Album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 8, 18, 20, 2, 706643, tzinfo=utc)),
        ),
    ]
