# Generated by Django 2.2.4 on 2019-09-09 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20190910_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='data',
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 21, 58, 3, 209038, tzinfo=utc)),
        ),
    ]
