# Generated by Django 2.2.4 on 2019-10-03 22:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20191004_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 22, 25, 53, 486229, tzinfo=utc)),
        ),
    ]
