# Generated by Django 2.2.4 on 2019-10-04 01:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20191004_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 1, 51, 17, 57771, tzinfo=utc)),
        ),
    ]
