# Generated by Django 2.2.4 on 2019-10-04 01:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20191004_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 1, 54, 23, 505797, tzinfo=utc)),
        ),
    ]
