# Generated by Django 2.2.4 on 2019-12-28 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_auto_20191228_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 17, 26, 57, 934539, tzinfo=utc)),
        ),
    ]
