# Generated by Django 2.2.4 on 2019-12-28 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_auto_20191228_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 17, 29, 39, 683642, tzinfo=utc)),
        ),
    ]
