# Generated by Django 2.2.4 on 2020-01-04 21:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0032_auto_20191229_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 21, 43, 18, 764643, tzinfo=utc)),
        ),
    ]
