# Generated by Django 2.2.4 on 2020-01-04 22:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0034_auto_20200105_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 22, 9, 6, 442607, tzinfo=utc)),
        ),
    ]
