# Generated by Django 2.2.4 on 2020-01-04 23:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0041_auto_20200105_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 23, 41, 20, 370415, tzinfo=utc)),
        ),
    ]
