# Generated by Django 2.2.4 on 2020-01-05 00:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0045_auto_20200105_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 0, 27, 9, 757629, tzinfo=utc)),
        ),
    ]
