# Generated by Django 2.2.4 on 2020-01-05 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0046_auto_20200105_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 18, 31, 39, 683946, tzinfo=utc)),
        ),
    ]
