# Generated by Django 2.2.4 on 2020-01-07 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0053_auto_20200107_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 11, 51, 4, 714134, tzinfo=utc)),
        ),
    ]
