# Generated by Django 2.2.4 on 2020-01-07 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0054_auto_20200107_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 11, 55, 53, 988959, tzinfo=utc)),
        ),
    ]
