# Generated by Django 2.2.4 on 2020-01-24 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0065_calendarApp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 18, 36, 57, 30107, tzinfo=utc)),
        ),
    ]
