# Generated by Django 2.2.4 on 2020-01-24 21:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0069_auto_20200124_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 21, 43, 5, 789599, tzinfo=utc)),
        ),
    ]
