# Generated by Django 2.2.8 on 2020-02-07 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0070_auto_20200125_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 7, 28, 30, 400321, tzinfo=utc)),
        ),
    ]
