# Generated by Django 2.2.8 on 2020-02-05 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0071_auto_20200201_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 20, 3, 23, 240125, tzinfo=utc)),
        ),
    ]
