# Generated by Django 2.2.8 on 2020-02-07 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0071_auto_20200207_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 7, 31, 30, 701213, tzinfo=utc)),
        ),
    ]
