# Generated by Django 2.2.8 on 2020-02-05 20:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0072_auto_20200205_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 20, 9, 39, 129666, tzinfo=utc)),
        ),
    ]
