# Generated by Django 2.2.4 on 2019-08-16 20:42

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(default='C:\\Users\\Philip\\desktop\\music_site\\music_site\\music_site\\music\\static\\music\\image\\empty.png', upload_to='avatars'),
        ),
    ]
