# Generated by Django 2.2.4 on 2019-08-17 14:36

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190816_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='default.png', upload_to='avatars'),
        ),
    ]
