# Generated by Django 2.2.4 on 2019-08-20 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_favouritemusic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteMusic',
        ),
    ]
